= Putra Danish - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images/iamputradanish.png
:stylesDir: ../stylesheets

== PROJECT: Police Records System

---

== Overview

The police database is for police officers(PO) and headquarter personnel(HQP). Both groups will have varying access and authorization levels to this database. POs would be able to read from the database after screening someone while on patrol and choose his course of action base on the status/threat level of subject. HQP would have the added functions of adding and removing people from the database. Refer to quick start to get started

== Summary of contributions

* *Major enhancements*: added *log in ability using only passwords* & *the ability for HQP to update any password* 
** What they do: 
** *Password Accessibility* : allows HQP and PO to log into their respective profiles using just a password and without username. Once logged in, PO is not allowed to perform certain commands.
** *Update Password* : allows HQP to update any password, including PO passwords to new alphanumeric passwords with minimum length 5 characters.
** Justification: Since we don't want POs to alter the records, certain commands are disabled for them. The ability to update passwords regularly allows for greater security. 
The ability to lock anytime also helps to increase security in times of emergencies. Together, the features ensure a secure information-sensitive product.
** Highlights: Passwords had to be stored with encryption, and only allows user to enter incorrect passwords 5 times before shutting down.
** Credits: NIL

* *Minor enhancement*: added a lock command that allows any user to lock (log out) the device immediately at any time.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Managed all project releases `v1.1` - `v1.4` (4 releases) on GitHub
*** Managed all versions of product, and dissemination of all issues to team members
** Enhancements to existing features:
*** Updated the GUI color scheme (Pull requests https://github.com[#33], https://github.com[#34])
*** Wrote additional tests for implemented features to increase coverage from 30% to 35% (Pull requests https://github.com[#36], https://github.com[#38])
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]
*** Added use cases for implemented features in Developer Guide : https//github.com[#15]
** Community:
*** PRs reviewed : https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=password]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=use cases]
